# Congressional Coalition Tracker Configuration

# Database Configuration
database:
  url: "${DATABASE_URL}"  # Use environment variable for security
  pool_size: 10
  max_overflow: 20
  pool_recycle: 3600

# Data Sources
data_sources:
  govinfo:
    base_url: "https://www.govinfo.gov/bulkdata/BILLSTATUS"
    api_key_env: "GOVINFO_API_KEY"
  
  house_clerk:
    base_url: "https://clerk.house.gov/evs"
  
  senate_lis:
    base_url: "https://www.senate.gov/legislative/LIS/roll_call_votes"

# Analysis Settings
analysis:
  # Coalition detection
  coalition:
    vote_weight: 0.6
    cosponsor_weight: 0.3
    amendment_weight: 0.1
    min_coalition_size: 2
    method: "louvain"  # or "dbscan"
  
  # Outlier detection
  outlier:
    party_line_threshold: 0.8
    model_z_threshold: 2.0
  
  # Time windows
  default_window_days: 90
  long_window_days: 365

# Output Settings
output:
  default_dir: "data/results"
  save_individual: true
  format: "json"

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/congressional_coalitions.log"


