name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Optional lighter installs if available
          if [ -f requirements-web.txt ]; then pip install -r requirements-web.txt || true; fi
          if [ -f requirements-minimal.txt ]; then pip install -r requirements-minimal.txt || true; fi

      - name: Run tests (pytest)
        env:
          DATABASE_URL: sqlite:///:memory:
          FLASK_ENV: testing
          DEV_MODE: 'true'
        run: |
          # Exclude network-dependent script discovery
          pytest -q -k 'not senate_votes'


